### ISSUE TITLE
REST To-Do

### ISSUE THREAD

**Issue by TTtie** [zorbyte/Socus#19]
This is a list of REST endpoints that most likely won't come with Denocord v0.0.2 but should still be tracked and implemented if needed or relevant PRs are merged.
  - [ ] Create Guild Integration (watch [discord-api-docs/#2087](https://github.com/discord/discord-api-docs/pull/2087/files/..))
  - [ ] Modify Guild Integration (^)
  - [ ] Delete Guild Integration (^)
  - [ ] Sync Guild Integration (^)
- [ ] [Templates](https://discord.com/developers/docs/resources/template)
- [ ] Review ratelimiter implementation (while it works for most cases, I am a bit lost)
- [ ] Slash commands
- [ ] T. I. A. A. R. I. (Tear It Apart And Redo It)
